# -*- coding: utf-8 -*-
"""pracQipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCaMnFrVfwNIqXXFYKvPawQ0QH7zo2gL
"""

num1 = int(input("Enter first integer: "))
num2 = int(input("Enter second integer: "))

print(f"Sum: {num1 + num2}")
print(f"Difference: {num1 - num2}")
print(f"Product: {num1 * num2}")
print(f"Division: {num1 / num2 if num2 != 0 else 'Error: Division by zero'}")
print(f"Num1 is {'Even' if num1 % 2 == 0 else 'Odd'}")
print(f"Num2 is {'Even' if num2 % 2 == 0 else 'Odd'}")
print(f"Num1 as float: {float(num1)}")

sentence = input("Enter a sentence: ")
vowels = "aeiouAEIOU"
v_count = sum(1 for char in sentence if char in vowels)
c_count = sum(1 for char in sentence if char.isalpha() and char not in vowels)

print(f"Vowels: {v_count}, Consonants: {c_count}")
print(f"Reversed: {sentence[::-1]}")
print(f"Underscored: {sentence.replace(' ', '_')}")
print(f"Capitalized: {sentence.title()}")

tup1 = (1, "hello", 3.5, 10, "world")
# Filter numeric values
numeric_tup = tuple(x for x in tup1 if isinstance(x, (int, float)))
print(f"Filtered: {numeric_tup}")

# Attempt modification (Tuples are immutable)
try:
    tup1[0] = 100
except TypeError as e:
    print(f"Modification Error: {e}")

tup2 = (99, 100)
print(f"Concatenated: {numeric_tup + tup2}")

marks = {"Alice": 85, "Bob": 90}
marks["Charlie"] = 78       # Add
marks["Alice"] = 95         # Update
del marks["Bob"]            # Delete

print(f"Keys: {marks.keys()}")
print(f"Values: {marks.values()}")
print(f"Items: {marks.items()}")

words = ["level", "python", "radar", "machine learning"]
# Sort by length
words.sort(key=len)
# Identify palindromes
palindromes = [w for w in words if w == w[::-1]]
# Replace spaces with hyphens
hyphenated = [w.replace(" ", "-") for w in words]

print(f"Sorted: {words}\nPalindromes: {palindromes}\nHyphenated: {hyphenated}")

mixed_tup = (5, 15, "data", 2, 20)
temp_list = list(mixed_tup)
# Remove integers less than 10
filtered_list = [x for x in temp_list if not (isinstance(x, int) and x < 10)]
final_tup = tuple(filtered_list)
print(f"Cleaned Tuple: {final_tup}")

records = {
    101: {"name": "Arun", "marks": [80, 70, 90]},
    102: {"name": "Sita", "marks": [95, 88, 92]}
}

for sid, data in records.items():
    avg = sum(data["marks"]) / len(data["marks"])
    print(f"{data['name']} Average: {avg:.2f}")

topper = max(records.values(), key=lambda x: sum(x["marks"]))
print(f"Topper: {topper['name']}")

contacts = {}
# Basic logic:
contacts["Police"] = "100"       # Add
print(contacts.get("Police"))     # Search
del contacts["Police"]            # Delete
print(contacts)                   # List

attendance = {}
while True:
    choice = input("\n1.Add 2.Remove 3.Display 4.Exit: ")
    if choice == '1':
        name = input("Enter Employee Name: ")
        attendance[name] = "Present"
    elif choice == '2':
        name = input("Enter Name to remove: ")
        attendance.pop(name, "Not found")
    elif choice == '3':
        print(attendance)
    elif choice == '4':
        break

students = []
num = int(input("How many students? "))
for _ in range(num):
    name = input("Name: ")
    roll = input("Roll: ")
    marks = int(input("Marks: "))
    students.append({"name": name, "roll": roll, "marks": marks})

pass_threshold = 40
passed = [s for s in students if s["marks"] >= pass_threshold]
print(f"Passed Students: {passed}")

menu = {"Burger": 50, "Fries": 30, "Coke": 20}
order_total = 0
print("Menu:", menu)
while True:
    item = input("Order item (or 'done'): ").title()
    if item == 'Done': break
    if item in menu:
        order_total += menu[item]
    else:
        print("Not on menu.")

tax = order_total * 0.05
print(f"Total Bill (with 5% tax): {order_total + tax}")

from collections import OrderedDict

class LRUCache:
    def __init__(self, capacity):
        self.cache = OrderedDict()
        self.capacity = capacity

    def get(self, key):
        if key not in self.cache: return -1
        self.cache.move_to_end(key)
        return self.cache[key]

    def put(self, key, value):
        if key in self.cache: self.cache.move_to_end(key)
        self.cache[key] = value
        if len(self.cache) > self.capacity:
            self.cache.popitem(last=False)

sentence = input("Enter sentence: ").lower()
chars = [c for c in sentence if c.isalnum()]
unique = [c for c in chars if chars.count(c) == 1]
print(f"Unique characters: {set(unique)}")

def power(base, exp):
    res = 1
    for _ in range(abs(exp)):
        res *= base
    return res if exp >= 0 else 1/res

print(power(2, 3))

s = input("Enter string: ")
print(f"Is Palindrome? {s == s[::-1]}")
vowels = consonants = digits = special = 0
for char in s:
    if char.isdigit(): digits += 1
    elif char.isalpha():
        if char.lower() in "aeiou": vowels += 1
        else: consonants += 1
    elif not char.isspace(): special += 1

print(f"V:{vowels}, C:{consonants}, D:{digits}, S:{special}")

class Student:
    def study(self): return "Studying..."
class Teacher:
    def teach(self): return "Teaching..."
class Admin:
    def manage(self): return "Managing school..."

class Book:
    def __init__(self, title):
        self.title = title
        print(f"Book '{self.title}' added.")
    def __del__(self):
        print(f"Book '{self.title}' removed from memory.")

b1 = Book("Python Basics")
del b1

class Logger:
    def __init__(self, path):
        self.f = open(path, "a")
    def log(self, msg, level="INFO"): # Overloading via default args
        self.f.write(f"[{level}] {msg}\n")
    def __del__(self):
        self.f.close()

class Vehicle:
    total_rented = 0
    def __init__(self, rate):
        self.rate = rate
    def rent(self, days):
        Vehicle.total_rented += 1
        return self.rate * days

class Car(Vehicle):
    def rent(self, days):
        return super().rent(days) + 50 # Extra insurance fee

c = Car(100)
print(f"Fee: {c.rent(2)}")
print(f"Total: {Vehicle.total_rented}")

class User:
    def __init__(self, username):
        self.username = username
    def __str__(self): return f"User: {self.username}"

class Post:
    total_posts = 0
    def __init__(self, content, author):
        self.content = content
        self.author = author
        self.comments = []
        Post.total_posts += 1
    def __str__(self): return f"Post by {self.author.username}: {self.content}"

u = User("Dev123")
p = Post("Hello World!", u)
print(p)